export const notes = [
    {type: "waiting", name: "Loan Cancellation", note: "Loan cancellation issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Repayment issue", note: "Repayment issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Tenure extension issue", note: "Tenure extension issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Disbursement issue", note: "Disbursement issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Application login issue", note: "Application login issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Delete account issue", note: "Delete account issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Bank account issue", note: "Bank account issue, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Incomplete query issue", note: "Incomplete query issue, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "loan status", note: "Regarding loan status, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "loan related concern", note: "Regarding loan related concern, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "loan closure", note: "Regarding loan closure, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "cashback details", note: "Regarding cashback details, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Fraud issue", note: "Fraud issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "Harassment issue", note: "Harassment issue, as ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "message proof", note: "Asked for message proof, and ticket was on waiting for customer response, and since there is no response hence resolved the ticket."},
    {type: "waiting", name: "NOC", note: "Regarding NOC, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "credit limit increase", note: "Regarding credit limit increase, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "loan rejection", note: "Regarding loan rejection, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "general query", note: "Regarding general query, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "repayment offer messages", note: "Regarding repayment offer messages, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "processing charges", note: "Regarding processing charges, as ticket was on waiting for customer response, since there is no response hence resolved the ticket."},
    {type: "waiting", name: "disbursement failed", note: "on hold tkt, since the disbursement is failed and cancelled, resolving the ticket."},
    {type: "waiting", name: "cx issue is resolved", note: "on hold tkt, since the cx issue is resolved, resolving the ticket."},
    {type: "pending", name: "Loan Cancellation", note: "On hold ticket, loan cancellation issue. hence keeping this ticket as resolved."},
    {type: "pending", name: "Repayment issue", note: "On hold ticket, loan repayment issue, hence keeping this ticket as resolved."},
    {type: "pending", name: "Disbursement issue", note: "On hold ticket, loan disbursement issue. hence keeping this ticket as resolved."},
    {type: "pending", name: "Application login issue", note: "On hold ticket, Application login issue, hence keeping this ticket as resolved."},
    {type: "pending", name: "Delete account issue", note: "On hold ticket, Account delete issue hence keeping this ticket as resolved."},
    {type: "pending", name: "Bank account issue", note: "On hold ticket, Bank account change issue, hence keeping this ticket as resolved."},
    {type: "pending", name: "Incomplete query issue", note: "On hold ticket, Incomplete Query, hence keeping this ticket as resolved."},
    {type: "pending", name: "loan status", note: "On hold ticket, loan status, hence keeping this ticket as resolved."},
    {type: "pending", name: "loan related concern", note: "On hold ticket, loan related concern, hence keeping this ticket as resolved."},
    {type: "pending", name: "loan closure", note: "On hold ticket, loan closure issue, hence keeping this ticket as resolved."},
    {type: "pending", name: "Fraud issue", note: "On hold ticket, Fraud issue, hence keeping this ticket as resolve."},
    {type: "pending", name: "Harassment issue", note: "On hold ticket, Harassment issue, hence keeping this ticket as resolved."},
    {type: "pending", name: "NOC", note: "On hold ticket, NOC, hence keeping this ticket as resolved."},
    {type: "pending", name: "loan rejection", note: "On hold ticket, Loan Rejection, hence keeping this ticket as resolved."},
    {type: "pending", name: "Concern of loan details", note: "On hold ticket, Concern of loan details. hence keeping this ticket as resolved."},
    {type: "pending", name: "Tenure extension issue", note: "On hold ticket, Repayment extension issue, hence keeping this ticket as resolved."},
]